theme:
  name: "Default Theme"
  key: "default"
  description: "The GreenDog Theme"
  url: "http://example.com"
  author: "Alexander Negoda"
  email: "alexander.negoda@gmail.com"
  version: "1.0"
assigns:
  defaults:
    vars:
      strapline: "test variable"
    collections:
      blogroll: "blogroll"
  layouts:
    site:
      vars:
        test: "test_key"


  
  

