theme:
  name: "Default Theme"
  key: "default"
  description: "The Default Theme based on Twitter Bootstrap."
  url: "https://github.com/greendog"
  author: "Alexander Negoda"
  email: "alexander.negoda@gmail.com"
  version: "1.0"
assigns:
  defaults:
    vars:
      my_var: "test variable"