config:
  name: "Sprockets"
  key: "sprockets"
  description: "The Default Theme based on Twitter Bootstrap and Rails Assets Pipeline"
  url: "http://github.com/shoponrails/spreefinery_default_theme/tree/sprockets"
  author: "Alexander Negoda"
  email: "alexander.negoda@gmail.com"
  version: "1.0"
assigns:
  vars:
    my_var: "test variable"
  logo: 'logo.png'
  colors:
    link_color: '#33ded3'
    primary_color: '#ff0055'
    secondary_color: '#333333'
